INSERT INTO CAFE_USER(USERID, PASSWORD, NAME, EMAIL)
VALUES ('TEST', '1234', '텟슷텃', 'TEST01@NAVER.COM');

INSERT INTO CAFE_USER(USERID, PASSWORD, NAME, EMAIL)
VALUES ('JHC1426', '1111', 'MANJU', '11111@GMAIL.COM');

INSERT INTO CAFE_ARTICLE(WRITER, TITLE, CONTENTS, CAFEUSERID)
VALUES ('MANJU', '테스트01', '테스트용 글 입니돵', 2);

INSERT INTO CAFE_ARTICLE(WRITER, TITLE, CONTENTS, CAFEUSERID)
VALUES ('텟슷텃', '테스트02', 'TEST가 작성한 TEST', 1);

INSERT INTO CAFE_REPLY(WRITER, CONTENTS, ARTICLEID)
VALUES ('텟슷텃', '테스트용 댓글 일지도?!?!?!?', 1);
