DROP TABLE IF EXISTS CAFE_USER, CAFE_ARTICLE, CAFE_REPLY CASCADE;
CREATE TABLE CAFE_USER
(
    ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERID   VARCHAR(20) UNIQUE NOT NULL,
    PASSWORD VARCHAR(20)        NOT NULL,
    NAME     VARCHAR(20)        NOT NULL,
    EMAIL    VARCHAR(50)        NOT NULL
);

CREATE TABLE CAFE_ARTICLE
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    WRITER     VARCHAR(20)  NOT NULL,
    TITLE      VARCHAR(50)  NOT NULL,
    CONTENTS   VARCHAR(500) NOT NULL,
    TIME       DATETIME     NOT NULL DEFAULT NOW(),
    DELETED    BOOLEAN               DEFAULT FALSE,
    CAFEUSERID BIGINT,
    FOREIGN KEY (CAFEUSERID) REFERENCES CAFE_USER (ID)
);

CREATE TABLE CAFE_REPLY
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    WRITER    VARCHAR(20)  NOT NULL,
    CONTENTS  VARCHAR(300) NOT NULL,
    TIME      DATETIME     NOT NULL DEFAULT NOW(),
    DELETED   BOOLEAN               DEFAULT FALSE,
    ARTICLEID BIGINT,
    FOREIGN KEY (ARTICLEID) REFERENCES CAFE_ARTICLE (ID)
);
